### PR TITLE
Disabled Zally linting on save

### PR DESCRIPTION
**Pull request by semonte**
Instead of linting on every save, require users to manually
trigger Zally validation.

image

image

### CODE REVIEW

**Comment by semonte** [comment]
@zalando/team-zally The paths have `~1` strings, what should I do with them?

**Comment by semonte** [comment]
Just discovered JSON Pointer syntax at https://tools.ietf.org/html/rfc6901, nevermind :)

**Comment by maxim-tschumak** [comment]
Great! Let's ship it :)

**Comment by maxim-tschumak** [comment]
:+1:

**Review by maxim-tschumak — APPROVED** [review]

**Comment by semonte** [comment]
@maxim-tschumak I think https://github.com/zalando/intellij-swagger/issues/192 should be implemented before releasing.

**Pull request merged**
