### PR TITLE
Update Swagger UI to 3.24.3

### PR DESCRIPTION
**Pull request by oleynikandrey**

### CODE REVIEW

**Comment by fstorz** [comment]
Maybe an update to the most current bugfix version (3.23.6) might be better ;)
https://github.com/swagger-api/swagger-ui/releases

**Comment by kohlerdominik** [comment]
I would really appreciate if 3.23.0 or newer could get merged (supports multiple examples now).

@oleynikandrey maybe you can update PR to 3.23.6 or 3.23.8, there are several issues resolved?

**Comment by DominikBasnerSotec** [comment]
Any news on this? would be really great

**Review by DominikBasnerSotec — APPROVED** [review]
Updates the external files for swaggerui

**Comment by oleynikandrey** [comment]
I've updated Swagger UI to the latest version.
While this pull request isn't merged it's possible to build the plugin by hand:

1. Clone the repository `git clone https://github.com/oleynikandrey/intellij-swagger.git`
2. `cd intellij-swagger`
3. `./gradlew buildPlugin`. Plugin will be built here `build/distributions/intellij-swagger.zip`
4. [Install plugin from disk](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk).

**Comment by oleynikandrey** [comment]
@zeitlinger, @tkrop,  @semonte could someone of you approve this pull request?

**Comment by zeitlinger** [comment]
@oleynikandrey please fix the build error first.

**Comment by oleynikandrey** [comment]
@zeitlinger, fixed.

**Comment by zeitlinger** [comment]
:+1:

**Review by zeitlinger — APPROVED** [review]

**Comment by kohlerdominik** [comment]
Thanks very much for merging this. Would you mind to create a release from it, so it's available in the IDEs PluginManager?

**Pull request merged**
