### PR TITLE
Added an icon for OpenAPI 3

### PR DESCRIPTION
**Pull request by semonte**
Cropped the text from the OpenAPI 3 logo, so that it can be
used as an icon. This is permitted; the style guide at
https://www.openapis.org/faq/style-guide states:

_"the lettering may be omitted where a purely graphical
representation is required."_.

image

image

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by semonte** [comment]
👍

**Comment by semonte** [comment]
Thanks @maxim-tschumak I think you need to approve the PR instead of a thumb :)

**Review by maxim-tschumak — APPROVED** [review]

**Comment by maxim-tschumak** [comment]
right.. :)

**Pull request merged**
