### PR TITLE
Update Swagger UI from 3.39.0 to 5.1.0.

### PR DESCRIPTION
**Pull request by asaarilahti**
https://github.com/swagger-api/swagger-ui/releases/tag/v5.1.0

The current version is ~2.5 years old.

The files are from swagger-ui-dist without changes, with exception of:
- [src/main/resources/swagger-ui/swagger-initializer.js](https://github.com/zalando/intellij-swagger/pull/369/files#diff-7d6a98955f98d06b72b0a6ba41b5284478f90e5c20b5b08000e6d1a84d299e6e)
- [src/main/java/org/zalando/intellij/swagger/file/SwaggerUiCreator.java](https://github.com/zalando/intellij-swagger/pull/369/files#diff-3ee81a76d92403e2a960747fa3009bd12e2856350700fa20a5bb7b4fc411d062)

### CODE REVIEW

**Comment by cberg-zalando** [comment]
Hmm… Now we have already two major version bumps. I now what Swagger UI is, but what actually happens by integrating it. To me, Java <> JS always sounds a bit scary.

**Comment by asaarilahti** [comment]
> Hmm… Now we have already two major version bumps. I now what Swagger UI is, but what actually happens by integrating it. To me, Java <> JS always sounds a bit scary.

It's used to render the previews. In general we just feed in the spec.

**Comment by cberg-zalando** [comment]
Okay. Any reason why this PR is then still in draft mode?

**Comment by asaarilahti** [comment]
> Okay. Any reason why this PR is then still in draft mode?

I was investigating an issue related to the preview not getting updated. However, it seems it happens with the master too, so not does not seems to be related to this change. So I guess we could merge this.

**Review by cberg-zalando — APPROVED** [review]

**Pull request merged**
