### PR TITLE
Support multiple specification files in a project

### PR DESCRIPTION
**Pull request by semonte**
This commit adds support for indexing and using multiple OpenAPI and Swagger spec files.

Part of #269

### CODE REVIEW

**Comment by semonte** [comment]
This PR also covers https://github.com/zalando/intellij-swagger/pull/271, they have overlapping code changes.

**Comment by semonte** [comment]
@zalando/team-intellij-swagger please review :)

**Comment by semonte** [comment]
@maxim-tschumak can someone from your team review the open PRs? I would like to make a new release soonish.

**Comment by semonte** [comment]
The main changes this PR introduces:

- switch to using a common API specification indexer with implementations for Swagger and OpenAPI. The specification files are indexed in the same manner, so it makes sense to use a common abstract class with implementations for the few differences the indexers have.

- switch to using a common API index service with implementations for Swagger and OpenAPI. The index is used in the same manner, so again it made sense to use a common abstract class.

I hope someone is able to review the open PRs and let me know if you have any questions!

**Review by maxim-tschumak — APPROVED** [review]

**Pull request merged**
