### PR TITLE
Support completion from workspace files

### PR DESCRIPTION
**Pull request by gayanper**
This will show definition in other workspace files in ref completions for definitions. Basically this add the definition in other files in the workspace to the end of the completion list.

### CODE REVIEW

**Comment by gayanper** [comment]
@zeitlinger Please review this PR and give you feedback.

**Comment by gayanper** [comment]
To start with I only add support for swagger, if things go well next I will try to add support for open API as well.

**Comment by gayanper** [comment]
Added support for openAPI as well.

**Comment by zeitlinger** [comment]
:+1:

**Comment by gayanper** [comment]
Please let me know what do you think about the PR. I’m not really sure its a good idea to start file paths with ./. Let me know your thoughts

**Comment by zeitlinger** [comment]
FYI: @tkrop is the official maintainer.

**Comment by gayanper** [comment]
Will create new PR with a separate branch

**Pull request closed without merging**
