### PR TITLE
Issue #298 : Added extension points for openAPI 3.0, extending which custom suggestions can be provided. Also added examples for the implementation of the new extension points.

### PR DESCRIPTION
**Pull request by iAbhi1995**
There are no extension points for the openapi(swagger 3.0), because of which custom suggestions for field and values in it cannot be supplied.

Added extension points for the openapi( swagger 3.0) -
  1. org.zalando.intellij.swagger.extensions.completion.openapi.OpenApiCustomFieldCompletionFactory
  2. org.zalando.intellij.swagger.extensions.completion.openapi.OpenApiCustomValueCompletionFactory

Also added the example for using the extension point for OpenApiCustomFieldCompletionFactory.
1. org.zalando.intellij.swagger.examples.extensions.zalando.field.completion.openapi
which contains a InfoCompletion class providing custom suggestions for the info field in openapi(swagger 3.0)

### CODE REVIEW

**Comment by semonte** [comment]
The PR looks good, thanks for the contribution @iAbhi1995. Unfortunately I no longer maintain this project, but I wish @zalando/team-intellij-swagger takes a look at this PR.

**Comment by iAbhi1995** [comment]
@zeitlinger can you please look into the pull request?

**Comment by zeitlinger** [comment]
:+1:

**Review by zeitlinger — APPROVED** [review]

**Comment by iAbhi1995** [comment]
Hey @zeitlinger / @semonte ,
Thanks for the approval. 
We are actually using the IntelliJ-Swagger plugin and are waiting for the new release with this functionality which supports extension points for OpenAPI 3.0
By when can we expect a release?

**Pull request merged**
